# SINGLE GRIPPER CONTROLLERS

controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

robotiq_gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    command_interface: position
    max_effort_interface: "robotiq_85_left_knuckle_joint/effort"
    max_effort: 50.0
    max_velocity_interface: "robotiq_85_left_knuckle_joint/velocity"
    max_velocity: 0.5
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

robotiq_activation_controller:
  ros__parameters:
    default: true


# LEFT GRIPPER CONTROLLERS

left_gripper/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

left_gripper/robotiq_gripper_controller:
  ros__parameters:
    joint: left_robotiq_85_left_knuckle_joint
    command_interface: position
    max_effort_interface: "left_robotiq_85_left_knuckle_joint/set_gripper_max_effort"
    max_effort: 50.0
    max_velocity_interface: "left_robotiq_85_left_knuckle_joint/set_gripper_max_velocity"
    max_velocity: 0.5
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

left_gripper/robotiq_activation_controller:
  ros__parameters:
    default: true

# RIGHT GRIPPER CONTROLLERS (Namespace: /right_gripper)

right_gripper/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

right_gripper/robotiq_gripper_controller:
  ros__parameters:
    joint: right_robotiq_85_left_knuckle_joint
    command_interface: position
    max_effort_interface: "right_robotiq_85_left_knuckle_joint/set_gripper_max_effort"
    max_effort: 50.0
    max_velocity_interface: "right_robotiq_85_left_knuckle_joint/set_gripper_max_velocity"
    max_velocity: 0.5
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

right_gripper/robotiq_activation_controller:
  ros__parameters:
    default: true
